export const Locations = {
  BagerHat: [
    "kochuwa",
    "chitolmari",
    "Fakirhat",
    "Bagerhat sadar",
    "mongla",
    "Morelganj",
    "Mollahat",
    "Rampal",
    "Shoron Khola",
  ],
  BandarBan: [
    "Ali Kadam",
    "Kalaghat",
    "Lama",
    "Naikong",
    "Rowangchhari",
    "Ruma",
    "Thanchi",
  ],  
  Barguna: [
    "Amtali",
    "Bamna",
    "Betage",
    "Barguna Sadar",
    "Patharghata",
    "Taltoly",
  ],
  Barisal: [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Barishal Bandor Thana",
    "Barishal Sadar",
    "Gauronadi",
    "Hijla",
    "Kotowali",
    "Mahendiganj",
    "Muladi",
    "Wazirpur powrosohba",
  ],
  Bhola: [
    "Bhola Sadar", 
    "Burhanuddin" ,
    "Char fashion", 
    "Dokkhin aicha", 
    "Doulatkhan", 
    "Tazumuddin",
    "Lalmohon",
  ],
  Bogura : [
    "Adamdigi",
    "Bogura Gabtoli",
    "Bogura Sadar",
    "Dhunat",
    "Dhupchachiya",
    "Kahalu",
    "Nandigram",
    "Sariakandi",
    "Sahajanpur",
    "Shantahar",
    "Sherpur",
    "Shibganj",
    "Shonatola",
  ],
  Brahmanbaria: [
    "Akhaura",
    "Ashuganj",
    "Bancharampur",
    "Bijoynagor",
    "Bancharampur Sadar",
    "Brahmanbaria Sadar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail",
  ],
  Chandpur: [
    "Chandpur Sadar",
    "Faridganj",
    "Haimchar",
    "Hajiganj",
    "Kachua(Chandpur)",
    "Matlab (North)(Chengarchar)",
    "Matlab (South)",
    "Shahrasti",
  ],
  ChapaiNababganj : [   
   "ChapaiNababganj Sadar",
   "Gomastapur",
   "Nachole",
   "Shibganj", 
  ],
  Chittagong: [
    "Agrabad",
    "Akbarsah",
    "Andarkilla",
    "Anowara",
    "Bakoliya Thana",
    "Bashkhali",
    "Bayezid",
    "Bowalkhali",
    "Bondor",
    "Chandanaish",
    "Chawkbazar",
    "Chittagang Sadar ghat",
    "Double Mooring",
    "East Jora",
    "EPZ",
    "Enayetpur",  
    "Fatichari",
    "Hathazari",
    "Halisahar",
    "Karnophuli",
    "Keranihat",
    "Khulsi",
    "Kotowali",
    "Lohagara",
    "Mirsarai",
    "Nasirabad",
    "Nazirhat",
    "New Market CTG",
    "Pahartali",
    "Panchlaish",
    "Patiya",
    "Ranguniya",
    "Rawzan",
    "Shandip",
    "Satkaniya",
    "Sitakundo",
    "Zorarganj"
  
  ],
  Chuwadanga : [
    "AlomDanga",
    "ChuwaDanga Sadar",
    "Damurhuda",
    "Darshana",
    "Doulatganj",
    "Jiban nagar",
  ],
  Coxs_Bazar: [
    "Chakoria",
    "Coxs Bazar Sadar",
    "Eidgaon",
    "Kutubdia",
    "Moheshkhali",
    "Pekua",
    "Ramu (Coxs Bazar)",
    "Teknaf",
    "Ukhia (Coxs Bazar)",
  ],
  Cumilla: [
    "B.Para",
    "Barura",
    "Burichang",
    "Comilla Cantonment",
    "Chandina",
    "Chaudda Gram",
    "Companiganj",
    "Cumilla Sadar",
    "Daudkandi",
    "Debidar",
    "Gouripur",
    "Homna",
    "Kotbari",
    "Loksham",
    "Lalmai",
    "MEgna",
    "Mia Bazar",
    "Monohorganj",
    "MudaffarGanj",
    "Murad Nagar",
    "Nangol Kot",
    "Sadar Dakhin",
    "Titas",
  ],
  Dhaka: [
    "Turag",
    "Tejkunipara",
    "Tejgaon",
    "Dhamrai",
    "Dhanmondi",
    "Doha",
    "Daraz office",
    "Dayaganj",
    "Nawabganj",
    "the south",
    "Nardda",
    "Naya Paltan",
    "Nakhalpara",
    "New Market",
    "Narinda",
    "New Eschaton",
    "Nikunj",
    "Niketan",
    "Polashi",
    "Pallavi",
    "Nilkhet",
    "Old Paltan",
    "preemption",
    "Farmgate",
    "Postgola",
    "Bakshibazar",
    "Banashree",
    "Banani",
    "Banani DOHS",
    "Ancestry",
    "Bashundhara",
    "Bashundhara - joar saha",
    "Badda - United City",
    "Badda - Beraid",
    "Badda - Magardia",
    "Badda - Madhya Badda",
    "Badda - Satarkul",
    "Baridhara",
    "Baridhara DOHS",
    "Banglabazar",
    "Bangla Matar",
    "Basabo",
    "Biman Bandar Thana",
    "Vatara",
    "Buet Campass",
    "Mothijheel",
    "Magbazar",
    "Mohakhali DHOS",
    "Mohakhali",
    "Malibag",
    "Maniknagar",
    "Mirpur",
    "Mirpur DOHS",
    "Mirpur-1",
    "Mirpur-10",
    "Mirpur-11",
    "Mirpur-12",
    "Mirpur-2",
    "mugda",
    "Mohammadpur",
    "Jatrabari",
    "Ramana",
    "Rampura",
    "Rayerbagh",
    "Rupnag",
    "Lakshi Bazar",
    "Lalbagh",
    "blushing",
    "Rayerbazar",
    "Shanirakhra",
    "Shantinagar",
    "Shahjadpur",
    "Rajarbagh",
    "Shahjanpur",
    "Shahbagh",
    "Shimrail",
    "Sukrabad",
    "Rajabazar",
    "Shere Bangla Nagar",
    "Shyampur",
    "Sadarghat",
    "Sabujbag",
    "Savar",
    "Shyamoli",
    "Siddheshwari",
    "Sutrapur",
    "Segun Bagicha",
    "Agargaon",
    "Azimpur",
    "manners",
    "Aftabnagar",
    "Ibrahimpur",
    "Islampur",
    "eschaton",
    "Uora- Sector 17",
    "Uora- Sector 18",
    "Eat the answer",
    "answer",
    "Uttara - Ranabola",
    "Uttara-Abdullah",
    "Uttara-Kaola",
    "Uttara-Kamarpara",
    "Uttara-Diabari",
    "Uttara-Baunia",
    "Elephant Road",
    "Wari",
    "KadamTala",
    "Kamalapur",
    "Art garden",
    "Kalyanpur",
    "Kaowranbazar",
    "cockerel",
    "Kazipara",
    "Kathalbagan",
    "Kafrul",
    "Kamrangirchar",
    "Kuril World Road",
    "Keraniganj",
    "Cantonment",
    "Khilkhet",
    "Khilkhet-Dumni",
    "Khilkhet-Namapara",
    "Khilkhet-patira",
    "Khilkhet-Pingcity",
    "Khilkhet-Barua",
    "Khilgaon",
    "Khilgaon - Gogan",
    "Khilgaon - Trimohani",
    "Khilgaon - Dakshingaon",
    "Khilgaon - Nandipara",
    "Khilgaon - Nasirabad",
    "Khilgaon - Begunbari",
    "Khilgaon - Meradia",
    "Khilgaon - Sheikh",
    "Gabbatli",
    "Gulshan-1",
    "Gulshan-2",
    "shooting range",
    "Gendaria",
    "Green Road",
    "Chowkazar",
    "Jigatala",
    "Jurain",
    "Tikatuli",
    "DU Campus",
    "Demra",
    "Demra - Amulya",
    "Demra - Kayetpara",
    "Demra - Bhavani",
    "Demra market",
    "Hathirpul",
    "Hazaribagh",
  ],
  Dinajpur:[
     "Biral",
     "Birampur",
     "Birganj",
     "Bochaganj",
     "Chirirbandar",
     "Dinajpur Sadar",
     "Fulbari",
     "Ghoraghat",
     "Hakimpur (Hili)",
     "Kaharol",
     "Khanshama",
     "Nawabganj Dinajpur",
     "Parbatipur",

  ],
  Faridpur : [
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrashan",
    "Faridpur Sadar",
    "Madukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha",

  ],
  Feni: [
    "Chagalnayya",
    "Daganbhuiyan",
    "Feni Sadar",
    "Fulgazi",
    "Parshuram",
    "Sonagazi",
  ],
  Gaibandha : [
    "Fulchhari",
    "Gaibandha Sadar",
    "Gobindaganj",
    "Palashbari",
    "Sadulllahpur",
    "Saghata",
    "Sundarganj",

  ],
  Gazipur: [
    "Bangla Bazar (Mawna)",
    "Awora khali ( kaliganj)",
    "Badhon (Pubail)",
    "Bagbari (Kashimpur)",
    "Bager bazar (Mawana-Gazipur)",
    "Baimail -Konabari (Gazipur)",
    "Barmi Sreepur (Gazipur)",
    "Barmi Sreepur (Sreepur )",
    "Baroipara (Kaliakoir)",
    "Bason Thana (Gazipur)",
    "Berenda(Kashimpur)",
    "Bhawal Government College (Gazipur)",
    "Bokhtarour ( kaliganj)",
    "Bolakar Mor (Maleker Bari)",
    "Boro Mosjid Road (Board Bazar)",
    "Borsha Hall (Gazipur Chowrasta)",
    "Bosuga (Pubail)",
    "Chondra (Kaliakoir)",
    "Chowrasta (Tongi)",
    "College gate (Pubail)",
    "Colombiya (Gazipur By Pass Road)",
    "Dalan bazar ( kaliganj)",
    "Dhaladia (Kapasia)",
    "Dhaladia Sreepur(Mawna Gazipur)",
    "Dhigir Chala (Gazipur Chowrasta)",
    "DUET (Joydebpur)",
    "Fulbaria bazar (Kaliakoir)",
    "Fuldi ( kaliganj)",
    "Gacha Bazar (Boro bari)",
    "Gacha Thana (Board Bazar)",
    "Gazipur Bypass",
    "Goalbari bazar (Kaliakoir)",
    "Gorgoria masterbari (Sreepur)",
    "Gorgoria Masterbari(Sreepur Gazipur)",
    "Great Wall Jame Masjid (Chandona Chowrasta)",
    "Hatimara-Kashimpur(Gazipur)",
    "Hoque Market (Gazipur By Pass Road)",
    "Hotapara (Mawan-Gazipur)",
    "Itahata (Chandona Chowrasta)",
    "IUT Road (Board Bazar)",
    "Jajhor (Board Bazar)",
    "Jalsukha -Baroipara (Kaliakoir)",
    "Jinumarket (Tongi Bus Stand)",
    "Jiter mor -Kashimpur (Gazipur)",
    "Jogitota ( Joydebpur)",
    "Joina Bazar (Sreepur)",
    "Jorpukur (joydebpur)",
    "Joyertek(Ambag Road-Konabari)",
    "Joyna Bazar (Sreepur Gazipur)",
    "Kabirpur (Kaliakoir)",
    "Kaliakoir Upazila(Gazipur)",
    "Kaliganj(Tongi)",
    "Kapasia (Gazipur)",
    "Kapasia Amraid (Kapasia)",
    "Kapasia Bazar (Kapasia)",
    "Kapasia Tok Noyon (Kapasia)",
    "Kashimpur Bazar (Gazipur)",
    "Kashimpur Bus Stop (Gazipur)",
    "Kashimpur Square(Gazipur)",
    "Kazi Market(Kashimpur)",
    "kenakata Goli (Gazipur Chowrasta)",
    "Khapara (Hossain Market)",
    "Kodda (Gazipur By Pass Road road)",
    "Kodda Bazar (Tongi)",
    "Kodda bridge (Gazipur Chowrasta)",
    "Konabari (Gazipur)",
    "Konabari Bus stand(Gazipur)",
    "Konabari collage Gate(Gazipur)",
    "Konabari Jail khana(Gazipur)",
    "Konabari Kuddus Nagar(Gazipur)",
    "Madhobpur(Kashempur)",
    "Malakerbari (Tongi)",
    "Mawna Chowrasta",
    "Mc Bazar (Mawna)",
    "Member Bari(Mawna Gazipur)",
    "Miraspara (Tongi Bus stand)",
    "Mirerbazar(Tongi)",
    "Mirjapur Masterbari(Gazipur)",
    "Modhumita (Tongi Station Road)",
    "Mogor Khal (Gazipur By Pass Road)",
    "Molla market-(Kashimpur)",
    "Mollapara(Kashimpur)",
    "Mouchak (Gazipur)",
    "Mouchak Bazar(Kaliakair)",
    "Mudafa (Tongi cherag Ali)",
    "Mukter Bari Road (Board Bazar)",
    "Najor (Gazipur Chowrasta)",
    "Navanar Mor (Gazipur By Pass Road)",
    "Nawjor (Gazipur)",
    "Nayanpur Sreepur (Gazipur)",
    "Pagar - Miraspara ( Tongi Bus Stand)",
    "Paler Math (Gazipur Chowrasta)",
    "Panishel(Kashimpur)",
    "Polagach Road (Board Bazar)",
    "Police Line (Gazipur Chowrasta)",
    "Pollibiddut-Konabari(Gazipur)",
    "Pollibidut (Chondra)",
    "Porabari Bazar (Gazipur)",
    "Porabari Bazar(Gazipur)",
    "Pubail(Tongi)",
    "Rail Gate (Tongi Station Road)",
    "Rajabari -Sreepur Road(Gazipur)",
    "Rajabari Sreepur (Gazipur)",
    "Rajendrapur Cantonment (Rajendrapur)",
    "Safari Park(Gazipur)",
    "Salna(Gazipur)",
    "Sardaganj-Kashimpur( Kaliakoir)",
    "Sattola Garments (Maleker Bari)",
    "Sawraid ( kaliganj)",
    "Shafipur (Kaliakoir-Gazipur)",
    "Shibbari (joydebpur)",
    "Shilmun (Tongi Station Road)",
    "Shimultoli (joydebpur)",
    "Shofipur Bus Stand (Kaliakair)",
    "Sorabo(Kashimpur)",
    "Sreepur Chowrasta (Mawna)",
    "Sultan Market - Kashimpur ( Kaliakoir)",
    "Sultan Market Kashempur (Kaliakoir)",
    "Sultan Market(Kashimpur)",
    "T & T - (Tongi Station Road )",
    "Telipara(Chandona Chowrasta)",
    "Ulokhola ( Kaliganj-Tongi)",
    "Vannara (mouchak-Gazipur)",
    "Vobanipur(Gazipur)",
    "Waltion Micro-Tech(Chondra)",
  ],
  Gopalganj: [
    "Gopalganj Sadar",
    "Kasiani",
    "Kotalipara",
    "Maksudpur",
    "Tungipara",
  ],
  Habiganj : [
    "Azmireeganj",
    "Bahubal",
    "Baniachong",
    "Chunarughat",
    "Habiganj Sadar",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
  ],
  Jamalpur : [
    "Bakshiganj",
    "Dewangonj",
    "Islampur",
    "Jamalpur Sadar",
    "Madarganj",
    "Melandaha",
    "Sarishabari",
  ],
  Jashore : [
    "Bagharpara",
    "Benapole",
    "Chaugachha",
    "Jessore Sadar",
    "Jhikargachha",
    "Keshabpur",
    "Monirampur",
    "Obhoynagar",  
    "Sarsa",
  ],
  Jhalokathi : [
    "Jhalokathi Sadar",
    "Kathalia",
    "Nalchhiti",
    "Rajapur", 

  ],
  Jhenaidah :[
    "Harinakundu",
    "Jhenaidah Sadar",
    "Kaligonj", 
    "Kotchandpur",
    "Maheshpur",
    "Shailakupa", 
  ],
  Joypurhat : [
    "Akkelpur",
    "Joypurhat Sadar",
    "Kalai",
    "Khetlal",
    "Panchbibi",
  ],
  Khagrachari : [
    "Dighinala",
    "Khagrachari Sadar",
    "Laksmichari",
    "Manikchari",
    "Matiranga",
    "Mohalchari",
    "Panchari",
    "Ramgor",
  ],
  Khulna : [
    "Batiaghata",
    "Boyra",
    "Chandkhali",
    "Dacope",
    "Daulatpur",
    "Digholia",
    "Dumuria",
    "Fultola",  
    "Khalishpur",
    "Khulna Sadar",
    "Kopilmuni",
    "Koyra",
    "Paikgachha Upozila",
    "Rupsha",
    "Sonadanga",
    "Tala Upozilla",
    "Terokhada",
  ],

  Kishoreganj: [
    "Austogram",
    "Bajitpur",
    "Bhairab",
    "Hosainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],
  Kurigram : [
    "Char Rajibpur",
    "Chilmari",
    "Kurigram Sadar",
    "Nagesshari",
    "Phulbari",
    "Rajarhat",
    "Rawmari",
    "Ulipur",  
  ],
  Kushtiya : [
    "Daulatpur",
    "Islamic University",
    "Khoksha",
    "Kumarkhali",
    "Kushtia Sadar",
    "Kushtia-Mirpur",
  ],
  Lakshmipur: [
    "Alexandar",
    "Kamalnagar",
    "Laksmipur Sadar",
    "Raipur (Lakshmipur)",
    "Ramganj",
    "Ramgati",
  ],
  LalMonirhat : [
    "Aditmari",
    "Hatibandha (Lalmonirhat)",
    "Kaliganj(Lalmonirhat)",
    "Lalmonirhat Sadar",
    "Patgram",
  ],
  Madaripur: [
    "Dasar Thana",
    "Kalkini Thana",
    "Madaripur Sadar",
    "Rajoir Thana",
    "Shibchar",
   
  ],
  Magura : [
    "Magura Sadar",
    "Mohammadpur",
    "Shalikha",
    "Sreepur",
  ],
  Manikganj: [
    "Daulatpur(Manikganj)",
    "Ghior",
    "Harirampur (Manikganj)",
    "Manikganj Sadar",
    "Saturia",
    "Shibalaya",
    "Singair",
  ],
  Meherpur : [
    "Gangni",
    "Meherpur Sadar",
    "Mujibnagar",
  ],
  Moulavibazar : [
    "Baralekha",
    "Juri",
    "Kamalganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal",
  ],
  Munshiganj: [
    "Alamin Bazar (Sreenagar)",
    "Baghra (Sreenagar)",
    "Baligaon (Munshiganj)",
    "Baluchar (Sirajdikhan)",
    "Bandura (Dohar)",
    "Baroykhali (Sreenagar)",
    "Bausia (Munshiganj)",
    "Boxsonagar (Nawabganj)",
    "Damla (Sreenagar)",
    "Dogachi Contonment (Sreenagar)",
    "Dohori (Munshiganj)",
    "Galimpur (Nawabganj)",
    "Gazaria (Munshiganj)",
    "Haridia (Louhajang)",
    "Holdia Bazar (Louhajang)",
    "Hossaindi (Munshiganj)",
    "Ichhapura Bazar (Sirajdikhan)",
    "Jamaldi (Munshiganj)",
    "Joypara (Dohar)",
    "Kacari (Munshiganj)",
    "Kartikpur (Dohar)",
    "Katakhali (Munshiganj)",
    "Kola (Sirajdikhan)",
    "Kolma (Munshiganj)",
    "Kuchiamora (Sirajdikhan)",
    "Kusumpur (Munshiganj)",
    "Lauhajang (Munshiganj)",
    "Loskorpur (Sreenagar)",
    "Malkhanagar (Sirajdikhan)",
    "Mawa (Louhajang)",
    "Mirkadim (Munshiganj)",
    "Muktarpur (Munshiganj)",
    "Munshir Hat (Munshiganj)",
    "Nawabganj Upazila",
    "Nimtola (Munshiganj)",
    "Rajanagar (Munshiganj)",
    "Rikabibazar (Munshiganj)",
    "Shekharnagar (Sreenagar)",
    "Singpara Bazar (Sirajdikhan)",
    "Sipahipara (Munshiganj)",
    "Sirajdikhan (Munshiganj)",
    "Sreenagar (Munshiganj)",
    "Super Market Mor (Munshiganj)",
    "Tangibari (Munshiganj)",
    "Tin Dokan (Sreenagar)",
    "Tontor (Sirajdikhan)",
    "Vaggokul (Sreenagar)",
    "Vaggyakul (Sreenagar)",
    "Voberchar (Munshiganj)",
  ],
  Mymensingh : [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gafargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Muktagachha",
    "Mymensingh Sadar",
    "Nandail",
    "Phulpur",
    "Trishal"
  ],
  Naongan : [
    "Atrai",
    "Bodolgachi",
    "Dhamairhat",
    "Manda",
    "Mohadebpur",
    "Naogaon Sadar",
    "Niyamatpur",
    "Porsha",  
    "Potnitola",
    "Raninagaor",
    "Sapahar",
  ],
  Narail : [
    "Kalia",
    "Narail - Lohagara",
    "Narail Sadar",
    "Terokhada",
  ],
  NarayanGanj: [
    "Araihazar Thana",
    "Baiddar Bazar (Sonargaon)",
    "Bandar (Modonpur)",
    "Bhuigor (Narayanganj)",
    "Bhulta (Rupganj)",
    "Chashara (Narayanganj)",
    "Chittagong Road (Narayanganj)",
    "Fatullah (Narayanganj)",
    "Jalkuri (Narayanganj)",
    "Kachpur (Modonpur Narayanganj)",
    "Modonganj (Bandar Naraynaganj)",
    "Modonpur Sadar (Modonpur)",
    "Morgapara (Sonargaon)",
    "Nabiganj (Bandar Narayanganj)",
    "Rupganj Thana",
    "Shanarpar (Narayanganj)",
    "Sibu market ( Narayanganj)",
    "Siddhirganj (Narayanganj)",
    "Signboard (Narayanganj)",
    "Sonargaon (Narayanganj)",
  ],
  Narsingdi: [
    "Alamin Bazar (Sreenagar)",
    "Baghra (Sreenagar)",
    "Baligaon (Munshiganj)",
    "Baluchar (Sirajdikhan)",
    "Bandura (Dohar)",
    "Baroykhali (Sreenagar)",
    "Bausia (Munshiganj)",
    "Boxsonagar (Nawabganj)",
    "Damla (Sreenagar)",
    "Dogachi Contonment (Sreenagar)",
    "Dohori (Munshiganj)",
    "Galimpur (Nawabganj)",
    "Gazaria (Munshiganj)",
    "Haridia (Louhajang)",
    "Holdia Bazar (Louhajang)",
    "Hossaindi (Munshiganj)",
    "Ichhapura Bazar (Sirajdikhan)",
    "Jamaldi (Munshiganj)",
    "Joypara (Dohar)",
    "Kacari (Munshiganj)",
    "Kartikpur (Dohar)",
    "Katakhali (Munshiganj)",
    "Kola (Sirajdikhan)",
    "Kolma (Munshiganj)",
    "Kuchiamora (Sirajdikhan)",
    "Kusumpur (Munshiganj)",
    "Lauhajang (Munshiganj)",
    "Loskorpur (Sreenagar)",
    "Malkhanagar (Sirajdikhan)",
    "Mawa (Louhajang)",
    "Mirkadim (Munshiganj)",
    "Muktarpur (Munshiganj)",
    "Munshir Hat (Munshiganj)",
    "Nawabganj Upazila",
    "Nimtola (Munshiganj)",
    "Rajanagar (Munshiganj)",
    "Rikabibazar (Munshiganj)",
    "Shekharnagar (Sreenagar)",
    "Singpara Bazar (Sirajdikhan)",
    "Sipahipara (Munshiganj)",
    "Sirajdikhan (Munshiganj)",
    "Sreenagar (Munshiganj)",
    "Super Market Mor (Munshiganj)",
    "Tangibari (Munshiganj)",
    "Tin Dokan (Sreenagar)",
    "Tontor (Sirajdikhan)",
    "Vaggokul (Sreenagar)",
    "Vaggyakul (Sreenagar)",
    "Voberchar (Munshiganj)",
  ],
  Natore : [    
  "Bagatipara",
  "Baraigram",
  "Gopalpur UPO",
  "Gurdaspur",
  "Naldanga - Natore",
  "Natore Sadar",
  "Singra",
    ],
  Netrokona : [
    "Atpara",
    "Barhatta",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohanganj",
    "Netrokona Sadar",  
    "Purbadhala",
    "Susang Durgapur",

  ],
  Nilphamari : [
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishoriganj",
    "Nilphamari Sadar",
    "Saidpur",
    "Taraganj",
  ],
  Noakhali: [
    "Begumganj",
    "Chatkhil",
    "Companiganj (Noakhali)",
    "Hatiya (Noakhali)",
    "Kabir Hat (Noakhali)",
    "Maijdee (Noakhali)",
    "Nijumdip (Hatiya)",
    "Senbag",
    "Sonaimuri",
    "Subarnachar (Noakhali)",
  ],
  Pabna : [
    "Aminpur",
    "Ataikula",
    "Atghoria",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Ishwardi",
    "Kasinathpur",  
    "Lalpur",
    "Pabna Sadar",
    "Pabna-Faridpur",
    "Sathia",
    "Sujanagar",
    "Tebuniya"
  ],
  Panchagarh : [
    "Atwari",
    "Boda",
    "Debiganj",
    "Panchagarh Sadar",
    "Tetulia",
  ],
  Patuakhali : [
    "Bauphal",
    "Dashmina",
    "Dumkee",
    "Gala chipa",
    "Kala para",
    "Khepupara",
    "Mohipur",
    "Patuakhali Sadar",  
    "Subidkhali",
  ],
  Pirojpur : [
    "Bhandaria",
    "Kaukhali",
    "Mathbaria",
    "Nazirpur",
    "Pirojpur Sadar",
    "Swarupkathi",
  ],
  Rajbari: [
    "Golanda",
    "Kalukhali",
    "Pangsha",
    "Rajbari Sadar",
  ],
  Rajsahi : [
    "Bagha",
    "Bagmara",
    "Banseshwar",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Katakhali",
    "Mohonpur",  
    "Paba",
    "Puthia",
    "Rajpara",
    "Rajshahi Sadar (Boalia)",
    "Shah Mokdum",
    "Sharda",
    "Taherpur"
  ],
  Rangamati: [
    "Baghaichari",
    "Barkal",
    "Belaichari",
    "Jurachari",
    "Kaptai",
    "Kaptai Kaptai Project",
    "Kaptai Nuton Bazar",
    "Kaptai Sadar",
    "Kawkhali (Rangamati)",
    "Langadu",
    "Naniarchar",
    "Rajasthali",
    "Rangamati Sadar",
  ],
  Rangpur : [
    "Badarganj",
    "Gangachara",
    "Haragach Thana",
    "Kaunia",
    "Mahiganj Thana",
    "Mithapukur",
    "Pirgachha",
    "Pirganj Thana",  
    "Porshurampur Thana",
    "Rangpur Cantonment",
    "Rangpur Sadar(Kotowali Thana)",
    "Tajhat Thana",

  ],
  Satkhira : [
    "Ashashuni Thana",
    "Debhata Thana",
    "Kalaroa",
    "Kaliganj",
    "Satkhira Sadar",
    "Shymnagar",
    "Tala Thana",
  ],
  Shariatpur: [
    "Angaria (Shariatpur Sadar)",
    "Bhedarganj",
    "Binodpur (Shariatpur Sadar)",
    "Chikondi (Shariatpur Sadar)",
    "Chitoliya (Shariatpur Sadar)",
    "Damudiya",
    "Domshar (Shariatpur Sadar)",
    "Gosairhat",
    "Naria",
    "Palong (Shariatpur Sadar)",
    "Rudrokor (Shariatpur Sadar)",
    "Shakhipur (Shariatpur)",
    "Shariatpur Sadar",
    "Sholpara (Shariatpur Sadar)",
    "Tulasar (Shariatpur Sadar)",
    "Zajira",
  ],
  Sherpur : [
    "Jhinaigati",
    "Nakla",
    "Nalitabari",
    "Sherpur Sadar",
    "Sreebardi",
  
  ],
  Shirajganj : [
    "Belkuchi",
    "Kamarkhanda",
    "Kazipur",
    "Rayganj",
    "Salonga",
    "Shahjadpur-Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",  
    "Ullapara",
    
  ],
  Sunamganj : [
    "Bishwamvarpur",
    "Chhatak",
    "Derai",
    "Dharmapasha",
    "Dowarabazar",
    "Jagnnathpur",
    "Jamalganj",
    "Salla",  
  ],
  Sylhet : [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companyganj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",  
    "Jaintapur",
    "Kanaighat",
    "Osmani Nagar",
    "Sylhet Sadar",
    "Zakiganj",
  ],
  Tangail: [
    "Bashail",
    "Bhuapur",
    "Delduar",
    "Dhalapara(Modhupur)",
    "Dhanbari(Modhupur)",
    "Garo Bazar(Modhupur)",
    "Ghatail Senanibash(Modhupur)",
    "Ghatail(Modhupur)",
    "Gopalpur (Tangail)",
    "Hamidpur(Modhupur)",
    "Jhorka(Modhupur)",
    "Kadomtoli(Modhupur)",
    "Kakraid(Modhupur)",
    "Kalihati",
    "Mirzapur",
    "Modhupur (Mymensingh)",
    "Nagarpur",
    "Sagordighi(Modhupur)",
    "Shakhipur",
    "Tangail Sadar",
  ],
  Takhurgaon : [
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
    "Ruhiya",
    "Thakurgaon Sadar",
  ],

} as const;

export type CityName = keyof typeof Locations;